# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 齐鲁工业大学开源软件镜像站

school: 齐鲁工业大学

brand: QLU Open Source Mirror

operator: 齐鲁工业大学网络信息中心
author: Qilu University of Technology Operation & Maintenance Department
desc: 致力于为校内用户提供高质量的开源软件镜像、Linux 镜像源服务，帮助用户更方便地获取开源软件。本镜像站由齐鲁工业大学网络信息中心网络运维部负责运行维护。

logo: true
meow_404: true
issue_tag: tuna
baseurl: "" # the subpath of your site, e.g. /blog
permalink: "/:categories/:title/"
url: "https://mirrors.qlunet.cn"
hostname: "mirrors.qlunet.cn"
urlv4: "https://mirrors4.qlu.edu.cn"
urlv6: "https://mirrors6.qlu.edu.cn"

homelink: "https://www.qlunet.cn"
hide_navbar: false
hide_download: false
hide_server_status: false

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false


sass:
    sass_dir: static/css

gems:
    - jekyll-babel
    - jekyll-sitemap
    - jekyll/fontawesome/svg
    - jekyll-minifier

babel_js_extensions: 'es6'

exclude: [Gemfile, Gemfile.lock, README.md, gen_robot.sh, vendor, geninfo/, gen_robot.sh, gen_desc.py, Dockerfile*]
# vim: ts=2 sts=2 sw=2 expandtab
